apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: repo-template-server-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: repo-template-server
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
